### PR TITLE
27 Recruiter Page- Live Career Fair w/ Students in Queue Component

### PR DESCRIPTION
**Pull request by denise-wang**
issue #27 recruiter page- live career fair w/ students in queue component
- added the live career fair page for recruiters
- this page includes the queue where students are waiting to meet with recruiter
- recruiter are able to join a meeting with a students and also view their resume/basic profile
- you can get to this page from the home page by clicking "get started" for recruiters, and then "join now" on the live career fairs section

for visual approval:

before considering backend feasibility:
27-recruiterpage

after considering backend feasibility:
27-recruiterpage-2

### CODE REVIEW

**Comment by denise-wang** [comment]
@sjoshi804 this is the frontend for the recruiter live career fair page! does this look feasible with the backend? lmk if you want any modifications made to this

**Comment by sjoshi804** [comment]
This looks good, but is a bit of an issue with respect to our backend functionality. 
In particular, there is no way to look at all students in a queue. 
What do you think about something like this instead?
Screen Shot 2020-11-10 at 1 53 03 PM

**Comment by sjoshi804** [comment]
We should probably discuss frontend tomorrow to clarify what pages since we figured out our API on sunday

**Comment by denise-wang** [comment]
> We should probably discuss frontend tomorrow to clarify what pages since we figured out our API on sunday

@sjoshi804 Okay, I changed the entire page to match what you have based on the image you attached above! It now has an editable form that has the student applicants' names, interests, notes, and resume. Also has a component card with time left, students remaining, and join now button that links to a Google meet. I attached another gif in the description! You can check it out there.

**Review by sjoshi804 — APPROVED** [review]
Looks perfect! Thanks!

**Pull request merged**
